### PR TITLE
Install dependencies package automatically

### PR DESCRIPTION
**Pull request by HazemKhaled**
this is not that solid way, but the only one till now as i know

### CODE REVIEW

**Comment by yomybaby** [comment]
Great! I really want to do that. :+1:

**Comment by yomybaby** [comment]
But re-launch is required, right?

**Comment by yomybaby** [comment]
Anyway, merged. 
If you find better way, please let me know or PR :smile: 

Thanks

**Comment by HazemKhaled** [comment]
Yes, you need to restart and i don't know another way, at least it'll work from second time ;)

Thanks for merag

**Pull request merged**
